---
  - name: Wait for system to be ready
    wait_for_connection:
      timeout: 300
      delay: 5
    register: wait_result

  - name: Update apt cache and install required packages
    block:
      - name: Update apt cache
        apt:
          update_cache: yes
          cache_valid_time: 3600
          force_apt_get: yes

      - name: Install required packages
        apt:
          name: "{{ packages }}"
          state: present
          force_apt_get: yes
        vars:
          packages:
            # - nginx
            # - docker.io
            # - docker-compose
            - curl
            - git
        retries: 3
        delay: 5
        register: pkg_install
        until: pkg_install is success

  - name: Configure hostname
    block:
      - name: Set system hostname
        hostname:
          name: "{{ inventory_hostname }}"
        register: hostname_result

      - name: Update /etc/hostname
        copy:
          content: "{{ inventory_hostname }}\n"
          dest: /etc/hostname
          owner: root
          group: root
          mode: '0644'

      - name: Update /etc/hosts
        lineinfile:
          path: /etc/hosts
          regexp: '^127\.0\.1\.1\s+'
          line: "127.0.1.1 {{ inventory_hostname }}"
          state: present

      - name: Verify hostname is set correctly
        command: hostname
        register: hostname_check
        changed_when: false
        failed_when: hostname_check.stdout != inventory_hostname

  # - name: Configure services
  #   async: 300  # Timeout de 5 minutos
  #   poll: 0     # No esperar a que termine (fire and forget)
  #   block:
  #     - name: Start and enable services
  #       service:
  #         name: "{{ item }}"
  #         state: started
  #         enabled: yes
  #       loop:
  #         - nginx
  #         - docker
  #       ignore_errors: yes

  #     - name: Allow HTTP on firewall
  #       ufw:
  #         rule: allow
  #         port: '80'
  #         proto: tcp
  #       ignore_errors: yes

  - name: Create a new file
    copy:
      dest: /root/newfile.txt
      content: "Talis! 🚀\n"
