---
version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errorlint
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck  # Includes gosimple functionality in v2
    - unconvert
    - unused
    # Note: 'typecheck' was present in v1 config but is not included here because it's not a linter
    # that can be enabled or disabled. It's a built-in mechanism for reporting Go compiler errors
    # that runs automatically.

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number

# Linter settings moved to linters-settings in v2
linters-settings:
  gosec:
    excludes:
      - G115
  revive:
    rules:
      - name: package-comments
        disabled: true
      - name: duplicated-imports
        severity: warning
      - name: exported
        arguments:
          - disableStutteringCheck

  goimports:
    local-prefixes: github.com/celestiaorg
