services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: talis
      POSTGRES_PASSWORD: talis
      POSTGRES_DB: talis
    ports:
      - "127.0.0.1:5432:5432" # bind to localhost
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U talis"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: ghcr.io/celestiaorg/talis:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    depends_on:
      - db

volumes:
  postgres_data:
