---
version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: talis
      POSTGRES_PASSWORD: talis
      POSTGRES_DB: talis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U talis"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: ghcr.io/celestiaorg/talis:latest
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=talis
      - DB_PASSWORD=talis
      - DB_NAME=talis
    depends_on:
      - db

volumes:
  postgres_data:
