---
- hosts: all
  become: true
  gather_facts: yes
  strategy: free
  tasks:
    - name: Import vars file
      include_vars: "vars/main.yml"

    - name: Setup
      import_tasks: "./stages/setup.yml"
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      tags:
        - setup
    
    - name: Payloads
      import_tasks: "./stages/payloads.yml"
      when: >
        (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and
        (hostvars[inventory_hostname].payload_present | default(false) | bool or hostvars[inventory_hostname].tar_archive_present | default(false) | bool)
      tags:
        - payloads

    - name: Volumes
      import_tasks: "./stages/volumes.yml"
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      tags:
        - volumes
