---
- name: Configure servers
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - docker.io
          - python3-pip
        state: present

    - name: Install Docker Python package
      pip:
        name: docker
        state: present

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Wait for system to be ready
      wait_for_connection:
        timeout: 300
        delay: 5
      register: wait_result

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
        force_apt_get: yes
        update_cache: yes
      loop:
        - nginx
        - docker-compose
        - curl
        - git
      retries: 3
      delay: 5
      register: pkg_install
      until: pkg_install is success

    - name: Start and enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nginx
        - docker
      ignore_errors: yes

    - name: Allow HTTP on firewall
      ufw:
        rule: allow
        port: "80"
        proto: tcp
      ignore_errors: yes

    - name: Create a new file
      copy:
        dest: /root/newfile.txt
        content: "Talis! 🚀\n"
