---
- name: Configure DigitalOcean droplet
  hosts: all
  become: yes
  gather_facts: no
  serial: 1
  tasks:
    - name: Wait for system to be ready
      wait_for_connection:
        timeout: 300
        delay: 5
      register: wait_result

    - name: Gather facts
      setup:

    - name: Wait for apt to be ready
      shell: |
        while fuser /var/lib/dpkg/lock >/dev/null 2>&1 || fuser /var/lib/apt/lists/lock >/dev/null 2>&1 || fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          echo "Waiting for other package manager to finish..."
          sleep 1
        done
        while ps aux | grep -i apt | grep -v grep > /dev/null; do
          echo "Waiting for other apt processes to finish..."
          ps aux | grep -i apt | grep -v grep
          sleep 5
        done
      register: apt_wait
      retries: 60
      delay: 3
      until: apt_wait.rc == 0
      changed_when: false

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
        force_apt_get: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
        force_apt_get: yes
        update_cache: yes
      loop:
        - nginx
        - docker.io
        - docker-compose
        - curl
        - git
      retries: 3
      delay: 5
      register: pkg_install
      until: pkg_install is success

    - name: Start and enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nginx
        - docker
      ignore_errors: yes

    - name: Allow HTTP on firewall
      ufw:
        rule: allow
        port: '80'
        proto: tcp
      ignore_errors: yes

    - name: Create a new file
      copy:
        dest: /root/newfile.txt
        content: "Talis! 🚀\n"
