---
name: Approve and Merge Dependabot PRs
on:
  # Since these PRs are opened by dependabot, we need to run on _target to grant permissions for secrets
  pull_request_target:

jobs:
  dependabot:
    name: "Approve and Merge Dependabot PRs"
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: CelestiaBot Approval
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          PAT: ${{secrets.PR_APPROVE_PAT_CB}} # might be able to remove this
          GH_TOKEN: ${{secrets.PR_APPROVE_PAT_CB}} # should be used automatically by gh cli
