name: Deploy to Production

on:
  workflow_run:
    workflows: ["Docker Build & Publish"]
    types:
      - completed
    branches:
      # Only trigger for tag-based workflows (releases)
      - 'refs/tags/**'
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_ref != '') ||
      github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy docker-compose file to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: ${{ secrets.DEPLOYMENT_DIR }}

      - name: Get release tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Update image tag and deploy
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: TAG=${{ steps.get_tag.outputs.TAG }}
          script: |
            cd ${{ secrets.DEPLOYMENT_DIR }}
            echo "[INFO] Deploying tag: ${{ steps.get_tag.outputs.TAG }}"
            sed -i "s|ghcr.io/celestiaorg/talis:.*|ghcr.io/celestiaorg/talis:${{ steps.get_tag.outputs.TAG }}|" docker-compose.yml
            docker compose pull
            docker compose up -d --force-recreate api
